### ISSUE TITLE
What license is kancolle-replay?

### ISSUE THREAD

**Issue by biikame** [KC3Kai/kancolle-replay#13]
What license is kancolle-replay?

**Comment by dragonjet** [comment]
hm that's right, didn't notice until now that it's missing a license file. let's have @fourinone41 decide. just tell which permissions to give to public and I'll generate the file for you

**Comment by c933103** [comment]
![image](https://cloud.githubusercontent.com/assets/1525293/15099905/07fa031c-1596-11e6-95fb-1cdb8dfbfb02.png)
so it is MIT license
