### ISSUE TITLE
CV Search Lights, Left side always advantage

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/kancolle-replay#16]
> Hello, can u fix these things from KC3 Emulator: 
> 1. CV can equip Search Ligh,
> 2. The Left side always got advantaved the Right side.

-- Vũ Bảo via Facebook fan page messaging

**Comment by c933103** [comment]
In actual kancolle gameplay, the left side are always more advantageous than the right hand side, because left hand side always attack first, so it is not a bug, i think.

**Comment by c933103** [comment]
And according to fourinone41, the simulator did not implement any equipment limitation.

**Comment by dragonjet** [comment]
As it is a simulator, we can decide to permanently not put limitations on equipping, as some might want to try/test planes on a DD or whatever. This should be able to do things that your normal game cannot (such as using abyss fleet as your own ship: the sim is not game-logical in the first place)
