### ISSUE TITLE
Replay not working with URL

### ISSUE THREAD

**Issue by Beregondz** [KC3Kai/kancolle-replay#26]
As many times in the past, loading image from url doesn't work anymore.
I tried both with gyazo and imgur 
http://i.imgur.com/ZRffNxf.png
https://i.gyazo.com/a067dca361a1cd2dbd4af1beba2ad7b2.png
But every time nothing shows up, except the message "Invalid URL" after a minute or so.
I tried many things, from removing http:// to loading it from page url 
http://kc3kai.github.io/kancolle-replay/battleplayer.html?fromImg=http://i.imgur.com/ZRffNxf.png
http://kc3kai.github.io/kancolle-replay/battleplayer.html?fromImg=http://i.gyazo.com/a067dca361a1cd2dbd4af1beba2ad7b2.png
nothing works; I also tried loading an old replay without airbases or combined and that I know for sure it worked back then, no results.
I have the suspicion that it breaks mostly after updates, happened in the past and usually during or right after events

**Comment by fourinone41** [comment]
It was a problem with crossorigin.me, which was used to load images from URL. It was acting strangely these last few weeks, sometimes working sometimes not. I've switched to a different proxy (cors-anywhere.herokuapp.com) and it seems to be stable so far.
