### ISSUE TITLE
Night CI never occurs in simulator mode

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/kancolle-replay#29]
I noticed that, no matter what, night battle cut-ins never seem to occur when a battle is being simulated, independently of high luck values, searchlights, star shells, they just never seem to happen.

source: https://github.com/KC3Kai/KC3Kai/issues/1676

**Comment by fourinone41** [comment]
@Carbonation Can you show me the fleet and setup you used? I tried torpedo, mixed, main gun, and secondary gun CI, and don't seem to be reproducing the issue.
