### ISSUE TITLE
"Error"

### ISSUE THREAD

**Issue by ghost** [KC3Kai/kancolle-replay#3]
I'm not sure if it's because [the production version](http://kc3kai.github.io/kancolle-replay/battleplayer.html) version hasn't been updated but I can't load [this file](http://i.imgur.com/hK0p2mg.png) with that replayer. The stack trace is

```

TypeError: data.api_ship_ke is undefined
Stack trace:
processAPI@http://kc3kai.github.io/kancolle-replay/player.js:429:1
loadCode/f@http://kc3kai.github.io/kancolle-replay/player.js:2370:4
loadCode@http://kc3kai.github.io/kancolle-replay/player.js:2384:7
loadImage/preview.onload@http://kc3kai.github.io/kancolle-replay/battleplayer.html:30:5
```

**Comment by dragonjet** [comment]
tagging people who might know more about battles @fourinone41 @Javran

**Comment by ghost** [comment]
I think it's because the replayer can't handle the new single airstrike node just like the extension in earlier versions.

**Comment by ghost** [comment]
Hm, or alternatively, my sortie was recorded in a version of KC3 kai that didn't properly record Henderson nodes
