### ISSUE TITLE
Fail to read sinked ship data

### ISSUE THREAD

**Issue by ghost** [KC3Kai/kancolle-replay#43]
**Details**
If there is any sinked ship in team, KC3-replay will make the last ship undefined in the next node

**Image**
Hiei was sinked but Kirishima got undefined
![imageedit_2_8666680827](https://user-images.githubusercontent.com/30903885/33516763-cc362d5a-d7aa-11e7-851f-c18692d15f57.png)

[**Replay**](http://kc3kai.github.io/kancolle-replay/battleplayer.html?fromImg=https://vignette.wikia.nocookie.net/kancolle/images/a/a8/FubakiChan_120.png/revision/latest?cb=20171202112534)

**I got permission from the author and post here although it's a sensitive topic because I think bug is bug and need to be reported**

**Comment by mikenzb** [comment]
Seems like this issue has been fixed already, will close issue.
