### ISSUE TITLE
some issue about sortie simulator

### ISSUE THREAD

**Issue by jerry78424** [KC3Kai/kancolle-replay#60]
Bug report:
1.Nagato and Mutsu's special shouldn't trigger when number2 BB is Taiha'd.
2.New depth charge projectors(+12 and +15 ones) do have synergy with sonar which works differently with old DCPs.

Request:
1.Add repair team/goddess comsuption in average resupply section.

**Comment by sinsinpub** [comment]
1. to prove such a case, 1 counterexample is not enough. 'should not trigger' needed to be proved by samples, do u have enough sample data?
2. the damage samples needed too. if it's different with 1.15, so what should it be?

**Comment by jerry78424** [comment]
> 
> 
>     1. to prove such a case, 1 counterexample is not enough. 'should not trigger' needed to be proved by samples, do u have enough sample data?

It just can't, you can check your battle logs or see if there is any screenshot that proves NagaMutsu SP could trigger with accompany BB in Taiha.

> 
>     2. the damage samples needed too. if it's different with 1.15, so what should it be?

Currently there is no 1.15 multiplier for new DCPs with sonar in simulator as it should be, for details you can see
https://wikiwiki.jp/kancolle/%E8%A9%A6%E8%A3%BD15cm9%E9%80%A3%E8%A3%85%E5%AF%BE%E6%BD%9C%E5%99%B4%E9%80%B2%E7%A0%B2
