### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by nyokkora** [KC3Kai/kancolle-replay#68]
1.If you use headquarters-type equipment, I guess that the current specifications allow you to evacuate any ship at any time. However, this cannot consider route branching such as search value. Therefore, I would like to be able to individually specify the ships that are allowed to evacuate and escort for each node, and set the maximum number of them.
2.Currently when I edit fleet info, I have to re-import the eval for each node. This is very time consuming. Therefore, I would like to have a function that allows you to set whether or not to grant special effects in advance, and automatically grant special effects when the fleet is edited (or when calculation starts).
3.I think that operability will be further improved if ships, equipment, and base air groups can be moved and replaced with a mouse drag.

This sentence uses machine translation. Please ask questions if anything is unclear.
Thanks for the great tools as always.

**Comment by fourinone41** [comment]
3 is already possible, if I understand correctly? You can drag ship's banners and equipment's icons to swap.
![image](https://user-images.githubusercontent.com/15643445/230711915-92e6c518-a9a6-4d88-822a-74b2ecf76af4.png)
![image](https://user-images.githubusercontent.com/15643445/230711991-6060254c-e3e0-475a-a6fb-e5a2d8dc62e3.png)

**Comment by nyokkora** [comment]
Sorry for my late reply.
I am glad that you responded.
The third was my lack of confirmation, sorry.

PS. As a small thank you, I will attach a tool that I usually use.
It might help if you aim to be ranked.
This tool does not interfere with the game itself at all.
So to speak, it is just a substitute for paper and pencil.
When using, download the senka_manager folder and open interface.html in your browser. I think you can understand it while you touch it.
https://drive.google.com/drive/folders/1ivgJ-byhMboB6Ba9VYacV7GEpqqdiALN

Thanks to you, I was able to clear the event on hard for the first time since returning. thanks so much.
