### ISSUE TITLE
bugs and requests

### ISSUE THREAD

**Issue by nyokkora** [KC3Kai/kancolle-replay#69]
1. When the Allied Fleet reaches the night battle square, wreckage is confirmed in the 1st Fleet of 'Destruction Rate Per Battle'. I do not know how reproducible it is, but I will attach the confirmed data.
2. When importing a formation from 'From text', the combined fleet seems to be set to Carrier Task Force by default. This is an element that greatly affects the battle, so it would be more helpful if the system recognized it or displayed a confirmation message.
thank you for always
![E5-3](https://user-images.githubusercontent.com/129803845/232612656-b26426e2-232c-4838-849c-1196cb7ea81c.jpeg)
The extension of the kcsim file is changed for github specifications.

**Comment by fourinone41** [comment]
1. I think this is because you have Fleet Command Facility. If a 1st fleet ship is taiha from previous node and retreated, it will still count as taiha on night battle node. Maybe better to show "newly became taiha" instead?

**Comment by fourinone41** [comment]
1. Now doesn't count retreated ships for taiha statistics.
2. When pasting deckbuilder json, now you choose exactly which fleet and type to import:
![image](https://user-images.githubusercontent.com/15643445/233844790-76234fbe-2449-4ed7-9751-dab170050412.png)
