### ISSUE TITLE
Air night attacks should ignore all anti-installation bonus

### ISSUE THREAD

**Issue by Billons007** [KC3Kai/kancolle-replay#70]
But the simulator didn't ignore anti-installation bonus in air night attacks
Source:[JP-Wiki](https://wikiwiki.jp/kancolle/%E5%AF%BE%E5%9C%B0%E6%94%BB%E6%92%83#AGCalcCVN),[EN-Wiki](https://en.kancollewiki.net/Combat/Anti-Installation#Night_Battle)

**Comment by fourinone41** [comment]
Can you show which ship+equipment vs which enemy you think should be changed?

As far as I know, simulator currently is consistent with jp wikiwiki:

simulator:
- normal formula attacks (e.g. Graf, Unyou): use anti-installation precap mod and Supply Depot postcap mod ([TsunDB proof](https://tsunkit.net/api/routing/battles/2253145/replay))
- air formula attacks (e.g. Saratoga, Ark, any CV with NOAP): ignore anti-installation precap mod, use Supply Depot postcap mod (no proof found for postcap)

wikiwiki:
- air attacks vs Artillery Imp/Isolated Island Princess: ignore divebomber/jet precap mod
- Taiyou-class with Type 2 Mortar: unconfirmed
- Gambier Bay with daihatsu: ignore anti-installation mods ([has source for Artillery Imp only](https://twitter.com/ych0701/status/1418611852230074371))

**Comment by Billons007** [comment]
this problem looks like only happend on Airfield Princess series, in simulator, When Gambier bay use 大発動艇(八九式中戦車&陸戦隊), 特大発動艇 一式砲戦車 etc. it still use the anti-installation precap mod.

**Comment by fourinone41** [comment]
Can't seem to reproduce, here is what I setup to test:
[KanColle_Sortie_Simulator_Backup_2023-07-07.txt](https://github.com/KC3Kai/kancolle-replay/files/11980844/KanColle_Sortie_Simulator_Backup_2023-07-07.txt) (had to rename .kcsim -> .txt to upload)

Can you show yours which has the problem?

**Comment by Billons007** [comment]
oh...i can't to reproduce this time, it looks like be fixed. (but why?) anyway it was running alright now.

**Comment by Billons007** [comment]
or maybe I'm just confusing it with critical hit? anyway thanks to reply.
